// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kufuqtpqiaupaxchdnsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZnVxdHBxaWF1cGF4Y2hkbnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MTEzNDMsImV4cCI6MjA2MTk4NzM0M30.y0I6UsR-wW73bNwBu4X91wwcLTC9V5gB2og1-m03RDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);